### ISSUE TITLE
FYI - script crash / hung kodi - extended info on tv show episode

### ISSUE THREAD

**Issue by mgonzales71** [phil65/script.extendedinfo#13]
kodi 14.2
windows 8.1 x64
skin: titan helix beta 3.3.3
extended info 2.0.9

selected get info on:
tv show "the flash" episode 19 
(using genesis add-on added to library)

caused kodi to hang - could not recover from spinning/busy indicator in skin - no key presses (escape, backspace, x, etc) could break out and return to skin control - waited 5 mins before killing process in windows.

error log excerpt:

22:36:15 T:2884  NOTICE: version 2.0.9 started
22:36:16 T:2884   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following erro
r<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.extendedinfo\defau
lt.py", line 62, in <module>
                                                Main()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.extendedinfo\defau
lt.py", line 26, in __init__
                                                StartInfoActions(self.infos, self.params)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.extendedinfo\resou
rces\lib\process.py", line 220, in StartInfoActions
                                                u'script-%s-DialogVideoInfo.xml' % ADDON_NAME, ADDON_PATH, tvshow=params
["tvshow"], season=params["season"])
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.extendedinfo\resou
rces\lib\DialogSeasonInfo.py", line 24, in __init__
                                                self.season = GetSeasonInfo(self.tmdb_id, self.showname, self.season)
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.extendedinfo\resou
rces\lib\TheMovieDB.py", line 610, in GetSeasonInfo
                                                tmdb_tvshow_id = str(response['results'][0]['id'])
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by phil65** [comment]
well I dont really support anything connected to genesis.
anyways, post a COMPLETE log on pastebin and I will have a look.

**Comment by mgonzales71** [comment]
here you are:  http://pastebin.com/5WsGQzbn

To not taint the issue and remove genesis from the equation:

- deleted/removed the existing folder from the library (the streams files from the addon that shall not be mentioned) :)
- downloaded a test video file, renamed it and placed it in the proper folder structure for the episode to scan into the library properly.
- added that folder as a new source setting TV shows as the content type 
- scanned the folder into the library

Here is a zip of the test source folder:  
https://dl.dropboxusercontent.com/u/2203431/TV%20Shows.zip

I verified the test file was scanned into the library properly by seeing it was available in TV Shows and playing a few seconds of the video file.

I was able to reproduce the hang 

Steps taken:

Selected TV Shows -> The Flash -> Episode 19 -> pressed (I)nfo then Select Extended Info - Hang

I was unable to regain control / response to keyboard commands after that in the Kodi application.

Was just presented with the skin's "busy" indicator

But I was able to put the app in "windowed" mode (by pressing \) and then click the close button which allowed the application quit without any errors presented to the windows GUI.

Hopefully the helps make your awesome script even better!

Thanks for writing it - very much love using it to find unknown gems to watch,

Let me know if I can provide you with any more info to assist with this issue.

Mario

**Comment by phil65** [comment]
that is no debug log, you have to turn on debug mode in settings.

**Comment by mgonzales71** [comment]
ok - sorry - give me a few mins.  

I was focusing on removing the add-on from the equation and giving you the COMPLETE log file and a test folder to reproduce the actual hang on your system if you wanted to.

brb

**Comment by mgonzales71** [comment]
The new debug log file was too big for paste bin so shared it via dropbox.

https://dl.dropboxusercontent.com/u/2203431/kodi%20%28extended%20info%20script%20error%29.log

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/script.extendedinfo/commit/bf9c1b9331e91c856b8817f405260745cda9c1d4

**Comment by mgonzales71** [comment]
yup :+1: - works like a charm.  :)  thanks sir!
