### ISSUE TITLE
"Premiered" empty label property

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#14]
"Premiered" label property is empty for Trakt.tv Trending items.

Let me know if you need a debug log.

Cheers
Nessus

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/script.extendedinfo/commit/8053ae035282a2622fb85026b2320e6e32e9459f

**Comment by Nessus85100** [comment]
Thanks, It's fixed for Movies but also the TVShows have the same problem.
I've try this : 'Premiered': tvshow['show']["first_aired"], but it gives me a script error.

Also can i ask if you had the time to look at this... https://github.com/phil65/script.skin.info.service/issues/2

**Comment by phil65** [comment]
didnt get any script errors by changing it: https://github.com/phil65/script.extendedinfo/commit/0bd1f04c4727050a182f43f279ac196ab267ee92

**Comment by Nessus85100** [comment]
That's true. It's fixed now and with no errors.
Obviously i did something wrong. 

Thanks
Nessus
