### ISSUE TITLE
Actors metadata integration

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#15]
Hi Phil
I am trying to replace Black's actors metadata script with yours and i want to ask you if is possible to add some property's that can help on hiding the DialogVideoInfo.xml:
https://github.com/Black09/script.metadata.actors/blob/master/README.txt#L62
https://github.com/Black09/script.metadata.actors/blob/master/resources/lib/dialoginfo.py#L464

Also is it possible to use the select dialog with the icon/thumb when there is more that one actor with the same name and you need to select the proper one ?. ATM you use the select dialog with the simple list, so it's kinda hard without the thumb to know which actor is the correct one.

Thanks
Nessus

**Comment by phil65** [comment]
added infodialogs.active property: https://github.com/phil65/script.extendedinfo/commit/6f16a32ad32df2c72435e3222500e4b6769d858a

showing thumbs in DialogSelect is a bit more work. Will put it on to-do list.

**Comment by Nessus85100** [comment]
Works great, thanks. If may ask for something more, id it possible not to close the infodialogs immediately clicking to open the next one but only when is filled with content ?. The reason that i am asking for this is because i hide the DialogVideoInfo.xml and when there no cached data the screen is empty until the the next script infodialog is filled and gets visible.

Also, is there a way to play the trailer of the movie directly from a button in script-ExtendedInfo Script-DialogVideoInfo.xml ?. I've try the code bellow but i get a kai message that there is no trailer when the movie is in library and a script error when is not...
<onclick>PlayMedia(plugin://script.extendedinfo/?info=playtrailer&&dbid=$ESCINFO[Window.Property(movie.DBID)])</onclick>

Thanks
Nessus

**Comment by phil65** [comment]
person images in DialogSelect done in https://github.com/phil65/script.extendedinfo/commit/7223ee648a22e4faebf70dcba6cd61928aeef84e

no, atm my system requires to close the previous dialog before opening a new one.

Why don't you post a log for the script error?

Did you try something like
RunScript(script.extendedinfo,info=playtrailer,id=PROPERTY_WITH_TMDB_ID) or
RunScript(script.extendedinfo,info=playtrailer,dbid=MOVIE_DBID) ?

**Comment by Nessus85100** [comment]
Person images works great, thanks.

For the trailer lunch RunScript(script.extendedinfo,info=playtrailer,id=$ESCINFO[Window.Property(movie.ID)]) works fine with both on-line and local items.

About the closing dialogs thing, please keep it in mind for whenever is possible to do it.

Thanks for all the help and changes.
Nessus
