### ISSUE TITLE
MPAA and Genres are missing from TV Shows

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#16]
MPAA and Genres properties are missing from TV Shows in script-ExtendedInfo Script-DialogVideoInfo.xml. Can you please add them ?.

Also are the tv shows properties the same as the movies ?. I mean for example the movie genre is... $INFO[Window.Property(movie.Genre)]. Will this also give an the tv show genre when the script opens a tv show infodialog ?. Is there a specific visible condition for the tv shows infolabels ?. I use now... IsEmpty(Window.Property(movie.TVShowTitle)) but i thought i should ask if this is the proper one.

EDIT: One more thing that i forged. When you open a movie from a home widget with info from TMDB (eg Popular Movies) and the movie is in local library the movie starts playing. But, when you do the same with a movie from TRAKT.tv (eg Trending Movies) the infodialog it's shows up. Can this to change to work like the items from TMDB ?

Thanks
Nessus

**Comment by phil65** [comment]
you can use Window.Property(type) (which can be "episode", "season", "tvshow", "movie")
Will have a look at the other stuff.

**Comment by phil65** [comment]
also added genre for tvshows now.

**Comment by Nessus85100** [comment]
Thanks for the tvshows genres. Window.Property(type) works fine. Will use that. Makes more sense.

By the way. The info=similarlocal gives me a script error. Here is a snippets of the error ... http://pastebin.com/XX68bZNR. Let me know if you need a full debug log.

Cheers
Nessus

**Comment by phil65** [comment]
please test similarlocal with https://github.com/phil65/script.extendedinfo/commit/47a78d42e43643bc7f55fa88d595041656a8a768 .

**Comment by Nessus85100** [comment]
It works but it fetches only one item. This is what i use to fetch the list...  <content>plugin://script.extendedinfo?info=similarlocal&amp;&amp;dbid=$INFO[ListItem.DBID]</content>.

Cheers
Nessus

**Comment by phil65** [comment]
should be fixed with https://github.com/phil65/script.extendedinfo/commit/3be7455abf039ab48ea8f6697e876dde64a980dc

**Comment by Nessus85100** [comment]
Yep, it's working fine now.

**Comment by phil65** [comment]
for trakt movies: please try https://github.com/phil65/script.extendedinfo/commit/930d589e6739ab7f18430226927109c7fd66ec5b

**Comment by phil65** [comment]
That TV Show stuff will take some time.
Please post exact script call you´re using.

**Comment by Nessus85100** [comment]
These are the script calls that i use:
`<content>plugin://script.extendedinfo?info=nearevents&amp;&amp;limit=20</content>`
`<content>plugin://script.extendedinfo?info=topartists&amp;&amp;limit=20</content>`

**Comment by phil65** [comment]
hmm does that one here help? https://github.com/phil65/script.extendedinfo/commit/80874296ef0b9badeca06acd14614b06191f07b0

**Comment by Nessus85100** [comment]
Yep, it's fixed. It works fine with lower and bigger limit values.

**Comment by phil65** [comment]
ok, will close this then. if you want then you can open a separate one for the stuff I didn´t fix / add yet.
