### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#19]
Something went wrong with the nearevents content listing.
Here is a snippet of the error... http://xbmclogs.com/ps6g8lvcv

I know you hate snippets but i think it's a simple fix. Let me know if you need a full debug log.

**Comment by phil65** [comment]
please try https://github.com/phil65/script.extendedinfo/commit/c3ac44cc73a6789ad787ed9ef0ab73240c5a7fe0

**Comment by Nessus85100** [comment]
Fixed. Thanks
