### ISSUE TITLE
imdb_id trakt.tv issue

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#20]
I use this visible condition to show an overlay if the item in the list is in local libary...
`<visible>!IsEmpty(ListItem.Property(imdb_id))</visible>`

Everything working fine for all list's form TMDB but in trakt.tv list's (Trending items) the property value is always filled (i've checked with an InfoLabel) even for the local items. This happens for both Movies and TV Shows lists.

Thanks
Nessus

**Comment by phil65** [comment]
? you should use ```<visible>!IsEmpty(ListItem.Property(dbid))</visible>``` for the local check.

**Comment by Nessus85100** [comment]
Yes, i know about that but i am using the same layouts and an amount of same variables and for the widgets with local items (Recent, Recommended etc) and i would like to avoid the extra visible condtions about this.

In case you've overlook (like the other time... lol) the imdb id is available in their api... http://docs.trakt.apiary.io/#reference/movies/trending/get-trending-movies

**Comment by phil65** [comment]
Again, you use imdb_id for local check? That doesnt make too much sense to me.

**Comment by phil65** [comment]
... and I already fetch imdb_id from Trakt: https://github.com/phil65/script.extendedinfo/blob/master/resources/lib/Trakt.py#L85

**Comment by Nessus85100** [comment]
>... and I already fetch imdb_id from Trakt: https://github.com/phil65/script.extendedinfo/blob/master/resources/lib/Trakt.py#L85

I don't understand... why then the property is not empty for any local items in the trakt.tv list's like they do in the TMBD list's ?

**Comment by phil65** [comment]
Me dont understand either ;) imdb_id is defnitely nothing you should use for a local check.

**Comment by Nessus85100** [comment]
I am using the same list layout's for all my Movies widgets. If i use ListItem.Property(dbid) then the overlay will show in all my widgets that provide local list's  (Recent, Recommended etc). That's i want to use that check. It's the opposite of checking for local items.

**Comment by phil65** [comment]
That wont work. There is no guarantee that trakt / TMDB returns a imdb id at all. What you would need is the dbid property with a different name.

**Comment by Nessus85100** [comment]
>There is no guarantee that trakt / TMDB returns a imdb id at all.

Aha,,, didn't now that. Sorry.
>What you would need is the dbid property with a different name.

Can you please add such property ?

**Comment by phil65** [comment]
just a guess: try checkin for property(file)

**Comment by Nessus85100** [comment]
Bingo !!!... working like charm... thanks a sorry for the inconvenience !!!.

Out of curiosity, where is that property ?... i don't  in scripts .py files.

**Comment by phil65** [comment]
look harder ;) local_db.py

**Comment by Nessus85100** [comment]
Indeed !. Next i will !!!

Cheers
Nessus
