### ISSUE TITLE
Fanart issue

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#22]
While you are in TMDB list window (script-ExtendedInfo Script-VideoList.xml), if you open one of the two infodialogs the fanart gets hidden. Is that a normal behavior ?

**Comment by phil65** [comment]
Sorry, missed this one.
The reason i think is that "Window.Property(abc)" refers to the topmost window/dialog, and not to the window/dialog it is used in. (I think that would be more intuitive)
I will take a closer look into it when i find some time. (very busy atm)

**Comment by phil65** [comment]
Also this one here closed. I would need a more detailed description of the problem if you want me to investigate this.
