### ISSUE TITLE
Window.Property(Biography) cuts off at comma

### ISSUE THREAD

**Issue by HitcherUK** [phil65/script.extendedinfo#31]
when used in text viewer via toolbox script but Window.Property(Plot) does not.

**Comment by phil65** [comment]
so it's probably a bug in toolbox script? could you check that?

**Comment by HitcherUK** [comment]
Not sure how to be honest. Every other instance of using the toolbox script's text viewer commas aren't a problem (ListItem.Plot, ListItem.Description, etc) it's just Window.Property(Biography).

**Comment by HitcherUK** [comment]
You're right, it is the toolbox script. I'll raise an issue for it. Thanks.
