### ISSUE TITLE
YouTube namespace issue

### ISSUE THREAD

**Issue by Nessus85100** [phil65/script.extendedinfo#32]
Hi Phil
I am getting a script error when i use youtube search in `<content>plugin://` if the search string has a namespace.
This is a snippet of the error... http://xbmclogs.com/pspsgptyr  but i can post a full debug log if it's needed.

I am on Isengard 15.2 and using the Helix branch of the script.

Thanks
Nessus

**Comment by phil65** [comment]
Hmm doesnt look like a namespace issue.
Do older versions work? Might also be that i finally reached my API limits, would have to check taht.

**Comment by phil65** [comment]
YouTube totally sucks in that aspect. :(

**Comment by Nessus85100** [comment]
No, the old versions give the same error too.

**Comment by phil65** [comment]
then I guess we have reached the API limit :/

**Comment by Nessus85100** [comment]
I notice that this commit https://github.com/phil65/script.extendedinfo/commit/9361a91039b419bf1b88bd34c466f2a3df72dacc is missing from Helix branch. Maybe is that the reason ?

**Comment by phil65** [comment]
no, that is just a rework, nothing in terms of functionality.

**Comment by phil65** [comment]
I only port over bugfixes to helix branch.

**Comment by Nessus85100** [comment]
If i get an new API key will fix the issue ?

**Comment by phil65** [comment]
should be. you could try out exchanging the key in YouTube.py. (please report back if that fixes it)

**Comment by Nessus85100** [comment]
ok, will do.

thanks

**Comment by Nessus85100** [comment]
New API key didn't help. Still getting the same error.

**Comment by Nessus85100** [comment]
And now also with strings with no namespace. eg "NBA" now also gives the same error

**Comment by Nessus85100** [comment]
By the way i've create a "Browser" key. Is that correct or do i need a different one ?

**Comment by phil65** [comment]
Hmm should work I think.
You could try putting a prettyprint(result) right before the exception occurs and check the actual value.

**Comment by phil65** [comment]
workin again or still broken?

**Comment by Nessus85100** [comment]
No. Is still broken. Didn't had the time to investigate it further.

**Comment by finalmakerr** [comment]
Try to replace space with %20.

**Comment by phil65** [comment]
If this still is an issue then please re-open and post all neccessary info. For now I close this.
