### ISSUE TITLE
 installing extended info script 

### ISSUE THREAD

**Issue by vincez28** [phil65/script.extendedinfo#33]
i keep getting a dependencies not met error when trying to install in kodi 15.2 isengard on firetv???

**Comment by phil65** [comment]
debug log?
How did you try to install?

**Comment by vincez28** [comment]
so I now have 3.1.2 version but shows available updates for 4.0.1. but when I tried to force update it shows Add-on is incompatible or has been marked broken in repo, dependencies not met, please contact add-on author

**Comment by phil65** [comment]
debug log?

**Comment by vincez28** [comment]
How would I get the debug log from the amazon firetv box where kodi 15.2 is installed?

**Comment by phil65** [comment]
I am not some help desk. You have to find out yourself.

**Comment by vincez28** [comment]
ok I have the log do i just copy and paste in this window?

**Comment by phil65** [comment]
http://www.pastebin.com

**Comment by vincez28** [comment]
ok I just uploaded the log in pastebin named extended info script

**Comment by phil65** [comment]
...you need to post a link to it. ;)

**Comment by vincez28** [comment]
http://pastebin.com/BH0y12vW

**Comment by phil65** [comment]
You have lot of piracy add-ons installed. I wont help you with that.

**Comment by vincez28** [comment]
What do u mean piracy addons? U mean 3 rd party addons?
Sent from Yahoo Mail on Android 
 
  On Mon, Jan 25, 2016 at 11:10 PM, Philipp Temminghoff<notifications@github.com> wrote:   
You have lot of piracy add-ons installed. I wont help you with that.
