### ISSUE TITLE
Syntax Error when opening addon

### ISSUE THREAD

**Issue by Tgxcorporation** [phil65/script.extendedinfo#35]
Hi, i'm getting this error opening the Extendend Info addon from Programs:

`13:29:49 T:123145308819456  NOTICE: version 4.5.1 started
13:29:49 T:123145308819456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/Users/massimo/Library/Application Support/Kodi/addons/script.extendedinfo/resources/lib/dialogs/DialogVideoList.py', 448, 55, '                filters = {item["type"]: item["id"] for item in self.filters}\n'))
                                            Traceback (most recent call last):
                                              File "/Users/massimo/Library/Application Support/Kodi/addons/script.extendedinfo/default.py", line 45, in <module>
                                                Main()
                                              File "/Users/massimo/Library/Application Support/Kodi/addons/script.extendedinfo/default.py", line 27, in __init__
                                                wm.open_video_list()
                                              File "/Users/massimo/Library/Application Support/Kodi/addons/script.extendedinfo/resources/lib/WindowManager.py", line 221, in open_video_list
                                                from dialogs import DialogVideoList
                                            SyntaxError: ('invalid syntax', ('/Users/massimo/Library/Application Support/Kodi/addons/script.extendedinfo/resources/lib/dialogs/DialogVideoList.py', 448, 55, '                filters = {item["type"]: item["id"] for item in self.filters}\n'))
                                            -->End of Python script error report<--
13:30:49 T:123145310429184 WARNING: DARWINOSX: underflow (0 vs 4096 bytes)
 `

Using Mac OS 10.11.3 - Kodi Jarvis 16.0 Final

**Comment by phil65** [comment]
please try https://github.com/phil65/script.extendedinfo/commit/4aeb64cee10fcaf8823bb60c84ec885f7378fe0a

**Comment by Tgxcorporation** [comment]
It's ok now.
Thanks
