### ISSUE TITLE
can't sort or filter pre-defined or user created movies lists 

### ISSUE THREAD

**Issue by samehvirus** [phil65/script.extendedinfo#40]
missing future or a bug, when browsing pre-defined movies list (like stared , rated ) or any user created movie list , you can't use sort by ( give you only option to sort by created date, no release date , rateing, or popularity options available to use   ) 

also if you try to choose any filters, like choosing genre, this will un-load your list , and filter all movies , instead of filter only the movies in your list .

hope you could look into this . it is a pain when you have a list of 800+ movie and can't control how is it displayed front of you.

version 5.1.0

**Comment by phil65** [comment]
Atm sorting is completely done by remote, and TheMovieDB only allows created_at sorting for lists. see http://docs.themoviedb.apiary.io/#reference/account/accountidfavoritemovies/get
