### ISSUE TITLE
Missing poster and has black background when using advancedsettings path substitution

### ISSUE THREAD

**Issue by woodside007** [phil65/script.extendedinfo#45]
I'm using a Nexus Player (Android) running the latest nightly. I have a networked source that I store all my movies and tv shows on.  I noticed when getting extended info on movies or tv shows that the background color of the info dialog takes colors from the poster and then uses those colors to render the background color. Very nice. I really like that.

I noticed that the Thumbnails directory in the userdata directory on the Nexus started to use a lot of space and being there is very little space to work with on the Nexus Player, I have used the advancedsetting xml to substitute the path like this...

`
<advancedsettings>
 <pathsubstitution>
  <substitute>
    <from>special://profile/Thumbnails/</from>
    <to>smb://192.168.1.11/Thumbnails/</to>
  </substitute>
 </pathsubstitution>
</advancedsettings>`

That works great and my thumbnails are going to the network share, but now since I substituted the thumbnail path, when getting extended info on a movie or tvshow the background is black. The data, actor thumbs, and everything else is all there but the background is black. Also, when browsing movies with the extendedinfo program browser itself and selecting a movie, the background is black and also no movie poster shows up. If I take the advanced settings file off the nexus so the thumbnails directory goes back to the nexus userdata directory all is fine again. I guess basically what i'm saying is that if you substitute the path of the thumbnails directory to a network share then you get a black background and no movie poster. Thanks.

**Comment by phil65** [comment]
Sorry, nothing I can do about that. It would need fixing in core.
