### ISSUE TITLE
why is this still broken?

### ISSUE THREAD

**Issue by drjohannspector** [phil65/script.extendedinfo#75]

**Comment by drjohannspector** [comment]
Maybe after months of forum posts about this not working, so somebody would have bothered to fix it.


Asking too much?

**Comment by drjohannspector** [comment]
You fucking suck

**Comment by drjohannspector** [comment]
I thought you would get the point when thousands of users are looking for 5.0.4 since you can't see to fix it. Why bother updating it if it still DOESN'T WORK!!

**Comment by drjohannspector** [comment]
pretty much ruining the Kodi experience. due to this POS!

**Comment by phil65** [comment]
lol.
